export const typeColors = {
  PLANTA: 'bg-green-500 text-white',
  FUEGO: 'bg-orange-500 text-white',
  AGUA: 'bg-blue-500 text-white',
  ELÉCTRICO: 'bg-yellow-400 text-slate-900',
  VENENO: 'bg-purple-500 text-white',
  NORMAL: 'bg-pink-300 text-slate-900',
  HADA: 'bg-pink-500 text-white',
  TIERRA: 'bg-amber-700 text-white',
  LUCHA: 'bg-red-700 text-white',
  PSÍQUICO: 'bg-pink-600 text-white',
  ROCA: 'bg-yellow-700 text-white',
  FANTASMA: 'bg-indigo-700 text-white',
  HIELO: 'bg-cyan-400 text-slate-900',
  DRAGÓN: 'bg-indigo-600 text-white',
  ACERO: 'bg-slate-400 text-slate-900',
  VOLADOR: 'bg-indigo-400 text-white',
  BICHO: 'bg-lime-600 text-white',
};

export const TYPE_TRANSLATIONS = {
  grass: 'PLANTA',
  poison: 'VENENO',
  fire: 'FUEGO',
  water: 'AGUA',
  electric: 'ELÉCTRICO',
  normal: 'NORMAL',
  fairy: 'HADA',
  ground: 'TIERRA',
  fighting: 'LUCHA',
  psychic: 'PSÍQUICO',
  rock: 'ROCA',
  ghost: 'FANTASMA',
  ice: 'HIELO',
  dragon: 'DRAGÓN',
  steel: 'ACERO',
  flying: 'VOLADOR',
  bug: 'BICHO',
};

export const backgroundColors = {
  PLANTA: 'bg-green-200',
  FUEGO: 'bg-orange-200',
  AGUA: 'bg-blue-200',
  ELÉCTRICO: 'bg-yellow-200',
  VENENO: 'bg-purple-200',
  NORMAL: 'bg-slate-200',
  HADA: 'bg-pink-200',
  TIERRA: 'bg-amber-200',
  LUCHA: 'bg-red-200',
  PSÍQUICO: 'bg-pink-200',
  ROCA: 'bg-yellow-200',
  FANTASMA: 'bg-indigo-200',
  HIELO: 'bg-cyan-200',
  DRAGÓN: 'bg-indigo-200',
  ACERO: 'bg-slate-300',
  VOLADOR: 'bg-indigo-200',
  BICHO: 'bg-lime-200',
};
